### PR TITLE
Kobi

### PR DESCRIPTION
**Pull request by MiniShark27**
Made a method to check if a user exists in the database with a given username/password
  - Currently searches the "Employees" table
  - If a user matches returns the user, otherwise false
  - Implemented into the already existing post request
    - Verified working (when the database is set up) via postman
  - Created testing file (jest) for the new method, and created a test to verify functionality
    - Test code works when run outside of test runner, otherwise gives an error about DB not being setup likely because the setup is async, will need to fix
  - Required methods that have not yet been implemented by the database team
    - Specifically, the drafted "isSetup" method and "reset" method

### CODE REVIEW

**Review by pokeblokdude — APPROVED** [review]
Doesn't seem like there's any issues

**Comment by pokeblokdude** [comment]
In 'Backend/databaseInterface.js', "model" is misspelled as "modal"

**Comment by MiniShark27** [comment]
Fixed spelling

**Review by thomas-hoyt — APPROVED** [review]
Looks good to me. Except for "modal" instead of "model" in databaseInterface.js, but it is consistent throughout.

**Pull request merged**
